from __future__ import annotations

import os
import random
import logging
import asyncio
from pathlib import Path
from typing import List, Dict

logger = logging.getLogger(__name__)

class ProxyEngine:
    """
    K1 Proxychains4 Dynamic Generator (Stage 21/25).
    Manages dynamic routing for offensive tools to ensure stealth and portability.
    """

    CONF_TEMPLATE = """
# proxychains.conf generated by K1 ProxyEngine
strict_chain
proxy_dns 
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000

[ProxyList]
{proxy_list}
"""

    def __init__(self, proxy_pool: List[Dict[str, str]] = None):
        self.proxy_pool = proxy_pool or []
        self.default_conf_path = Path("/etc/proxychains4.conf")
        self._lock = asyncio.Lock()

    def generate_config(self, mode: str = "random", count: int = 2) -> str:
        """
        Generates a proxychains configuration string.
        Modes: 'random' (for fuzzing), 'strict' (VPN-to-VPN for exploitation).
        """
        if not self.proxy_pool:
            logger.warning("Proxy pool is empty. Falling back to local routing.")
            return self.CONF_TEMPLATE.format(proxy_list="# Local routing (pool empty)")

        selected_proxies = []
        if mode == "random":
            # Select random proxies from the pool
            selected_proxies = random.sample(self.proxy_pool, min(count, len(self.proxy_pool)))
        elif mode == "strict":
            # Use all available VPN/High-reliability proxies in order
            selected_proxies = self.proxy_pool

        proxy_lines = []
        for p in selected_proxies:
            type_ = p.get("type", "socks5")
            host = p.get("host")
            port = p.get("port")
            user = p.get("user", "")
            pass_ = p.get("pass", "")
            
            line = f"{type_} {host} {port}"
            if user and pass_:
                line += f" {user} {pass_}"
            proxy_lines.append(line)

        return self.CONF_TEMPLATE.format(proxy_list="\n".join(proxy_lines))

    async def write_config(self, path: Path, mode: str = "random", count: int = 2):
        """Writes the generated configuration to a specific path with locking."""
        async with self._lock:
            config_content = self.generate_config(mode, count)
            path.parent.mkdir(parents=True, exist_ok=True)
            with open(path, "w") as f:
                f.write(config_content)
            logger.info(f"ProxyEngine: Config written to {path} (Mode: {mode})")

    @staticmethod
    def block_cloud_metadata():
        """
        Simulates egress filtering to block cloud metadata IPs.
        Requires root privileges to execute actual iptables commands.
        """
        logger.info("ProxyEngine: Blocking access to cloud metadata IP (169.254.169.254)")
        # In a real environment:
        # os.system("iptables -A OUTPUT -d 169.254.169.254 -j REJECT")
        pass

# Example usage
if __name__ == "__main__":
    # Mock proxy pool
    pool = [
        {"type": "socks5", "host": "1.2.3.4", "port": "1080", "user": "u1", "pass": "p1"},
        {"type": "socks5", "host": "5.6.7.8", "port": "1080", "user": "u2", "pass": "p2"},
        {"type": "http", "host": "9.10.11.12", "port": "8080"}
    ]
    engine = ProxyEngine(pool)
    engine.write_config(Path("proxychains.k1.conf"), mode="random", count=2)
