"""Add generated_reports table for storing generated PDF reports.

Revision ID: 0019_generated_reports
Revises: 0018_findings_database
Create Date: 2026-04-13

Creates:
    generated_reports — Store PDF reports generated by intelligence engine
"""
from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0019_generated_reports"
down_revision = "0018_findings_database"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create generated_reports table
    op.create_table(
        "generated_reports",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("report_type", sa.String(50), nullable=False),
        sa.Column("report_title", sa.String(500), nullable=False),
        sa.Column("report_description", sa.Text(), nullable=True),
        sa.Column("filters", postgresql.JSON(), nullable=False),
        sa.Column("pdf_content", sa.LargeBinary(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("generated_by", sa.String(255), nullable=False),
        sa.Column(
            "generated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("download_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_downloaded_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create indexes for efficient querying
    op.create_index("ix_generated_reports_report_type", "generated_reports", ["report_type"])
    op.create_index("ix_generated_reports_generated_by", "generated_reports", ["generated_by"])
    op.create_index(
        "ix_generated_reports_generated_at", "generated_reports", ["generated_at"]
    )


def downgrade() -> None:
    op.drop_index(
        "ix_generated_reports_generated_at", table_name="generated_reports"
    )
    op.drop_index("ix_generated_reports_generated_by", table_name="generated_reports")
    op.drop_index("ix_generated_reports_report_type", table_name="generated_reports")
    op.drop_table("generated_reports")
