#!/usr/bin/env python3
import os
import sys
import getpass
import secrets
import string

def generate_secret(length=32):
    return ''.join(secrets.choice(string.ascii_letters + string.digits) for i in range(length))

def prompt_user(question, default=None, is_secret=False):
    prompt_text = f"{question} "
    if default:
        prompt_text += f"[{default}]: "
    else:
        prompt_text += ": "
    
    if is_secret:
        value = getpass.getpass(prompt_text)
    else:
        value = input(prompt_text)
    
    if not value and default:
        return default
    return value.strip()

def main():
    print("\n" + "="*60)
    print("   KAISON K1 PLATFORM CONFIGURATION WIZARD")
    print("="*60 + "\n")

    env_path = ".env"
    existing_config = {}
    
    if os.path.exists(env_path):
        print(f"Found existing configuration at {env_path}. Values will be updated.")
        with open(env_path, 'r') as f:
            for line in f:
                if '=' in line and not line.startswith('#'):
                    k, v = line.strip().split('=', 1)
                    existing_config[k] = v

    # 1. AI Configuration
    print("\n--- AI Configuration ---")
    openai_key = prompt_user("Enter your OpenAI API Key (required for Kaison Composer/gpt-4.1)", 
                             default=existing_config.get("OPENAI_API_KEY"), is_secret=True)
    
    # 2. Network / Privacy Configuration
    print("\n--- Network & Privacy ---")
    use_whonix = prompt_user("Do you want to route tool traffic through a local Whonix Gateway?", default="no").lower()
    
    http_proxy = ""
    https_proxy = ""
    
    if use_whonix in ['y', 'yes', 'true', '1']:
        gateway_ip = prompt_user("Enter Whonix Gateway IP", default="10.152.152.10")
        gateway_port = prompt_user("Enter Whonix Gateway Port", default="9050") # Usually 9050 for Socks, 9080 for HTTP if configured
        
        # Note: Docker usually needs HTTP proxies. 
        # Ideally user has Privoxy or similar on Whonix Gateway for HTTP->Socks.
        # Assuming standard Whonix workstation config or similar:
        # We will set the proxy env vars.
        proxy_url = f"http://{gateway_ip}:{gateway_port}" # Assuming HTTP proxy available
        print(f"Configuring proxy to: {proxy_url}")
        http_proxy = proxy_url
        https_proxy = proxy_url
    else:
        print("Using direct connection (No Tor/Whonix).")

    # 3. generate secrets if missing
    print("\n--- Generating Secure Tokens ---")
    jwt_secret = existing_config.get("JWT_SECRET_KEY") or generate_secret(64)
    postgres_password = existing_config.get("POSTGRES_PASSWORD") or "k1password" # Keep default for dev simplicity if not changed
    
    # 4. Write .env file
    print(f"\nWriting configuration to {env_path}...")
    
    env_content = f"""# Kaison K1 Environment Configuration
# Generated by k1 setup wizard

# --- AI Providers ---
LLM_PROVIDER=openai
K1_PATCH_LLM_MODEL=gpt-4.1
OPENAI_API_KEY={openai_key}

# --- Infrastructure ---
POSTGRES_USER=k1
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB=k1
DATABASE_URL=postgresql://k1:{postgres_password}@postgres:5432/k1
REDIS_URL=redis://redis:6379/0

# --- Security & Secrets ---
JWT_SECRET_KEY={jwt_secret}
K1_DEV_TOKEN={existing_config.get('K1_DEV_TOKEN', 'k1-dev-token-docker')}
K1_SECRET_BACKEND=vault

# --- Proxy / Whonix Configuration ---
HTTP_PROXY={http_proxy}
HTTPS_PROXY={https_proxy}
# Pass these to worker container
K1_USE_DOCKER_SANDBOX=true

# --- Application Settings ---
DEBUG_MODE=true
ENVIRONMENT=development
LOG_LEVEL=INFO
"""
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print("Configuration complete!")
    print("You can now run './k1 start' to launch the platform.")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nConfiguration cancelled.")
        sys.exit(1)
