"""REST API endpoints for intelligent PDF report generation.

Provides endpoints for:
- Generating intelligent reports with custom specifications
- Downloading previously generated reports
- Querying report history
"""
from __future__ import annotations

import io
import logging
from datetime import datetime, timezone
from typing import Optional
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ..core.auth import get_current_user
from ..core.hil_db import get_db
from ..models.generated_reports import GeneratedReport
from ..models.report_spec import ReportSpecification
from ..services.report_intelligence_engine import ReportIntelligenceEngine

logger = logging.getLogger(__name__)

router = APIRouter(
    prefix="/api/v1/reports/intelligence",
    tags=["reports_intelligence"],
    dependencies=[Depends(get_current_user)],
)


@router.post("/generate")
async def generate_report(
    spec: ReportSpecification,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
) -> dict:
    """Generate intelligent PDF report based on specification.

    Analyst specifies:
    - Report type (per_scan, per_program, per_platform, etc.)
    - Data filters (programs, date ranges, vulnerability types, etc.)
    - Content preferences (sections, word count, charts)

    Engine returns:
    - Professional PDF (5-10K words)
    - Charts and visualizations
    - Intelligent narratives generated by Claude
    """
    spec.requested_by = current_user.get("user_id", "unknown")

    try:
        engine = ReportIntelligenceEngine(db)
        pdf_bytes = await engine.generate_report(spec)

        return {
            "status": "success",
            "message": f"Report generated: {spec.report_title}",
            "pdf_size_bytes": len(pdf_bytes),
            "report_type": spec.report_type.value,
        }

    except Exception as e:
        logger.error(f"Report generation error: {e}")
        raise HTTPException(
            status_code=500, detail=f"Report generation failed: {str(e)}"
        )


@router.get("/list")
async def list_reports(
    limit: int = 50,
    offset: int = 0,
    report_type: Optional[str] = None,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
) -> dict:
    """List previously generated reports.

    Args:
        limit: Maximum number of reports to return (default 50)
        offset: Number to skip (default 0)
        report_type: Filter by report type (optional)

    Returns:
        List of generated reports with metadata
    """
    query = select(GeneratedReport).offset(offset).limit(limit)

    if report_type:
        query = query.where(GeneratedReport.report_type == report_type)

    query = query.order_by(GeneratedReport.generated_at.desc())

    result = await db.execute(query)
    reports = result.scalars().all()

    formatted = [
        {
            "id": str(r.id),
            "report_type": r.report_type,
            "report_title": r.report_title,
            "generated_at": r.generated_at.isoformat() if r.generated_at else None,
            "generated_by": r.generated_by,
            "file_size_bytes": r.file_size_bytes,
            "page_count": r.page_count,
            "download_count": r.download_count,
            "last_downloaded_at": r.last_downloaded_at.isoformat()
            if r.last_downloaded_at
            else None,
        }
        for r in reports
    ]

    return {
        "reports": formatted,
        "total": len(formatted),
        "limit": limit,
        "offset": offset,
    }


@router.get("/{report_id}")
async def get_report_details(
    report_id: str,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
) -> dict:
    """Get details about a specific generated report."""
    try:
        report_uuid = UUID(report_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid report_id format")

    stmt = select(GeneratedReport).where(GeneratedReport.id == report_uuid)
    report = await db.scalar(stmt)

    if not report:
        raise HTTPException(status_code=404, detail="Report not found")

    return {
        "id": str(report.id),
        "report_type": report.report_type,
        "report_title": report.report_title,
        "report_description": report.report_description,
        "filters": report.filters,
        "generated_at": report.generated_at.isoformat() if report.generated_at else None,
        "generated_by": report.generated_by,
        "file_size_bytes": report.file_size_bytes,
        "page_count": report.page_count,
        "word_count": report.word_count,
        "download_count": report.download_count,
        "last_downloaded_at": report.last_downloaded_at.isoformat()
        if report.last_downloaded_at
        else None,
    }


@router.get("/{report_id}/download")
async def download_report(
    report_id: str,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
) -> FileResponse:
    """Download previously generated report as PDF.

    Args:
        report_id: Report UUID

    Returns:
        PDF file for download
    """
    try:
        report_uuid = UUID(report_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid report_id format")

    stmt = select(GeneratedReport).where(GeneratedReport.id == report_uuid)
    report = await db.scalar(stmt)

    if not report:
        raise HTTPException(status_code=404, detail="Report not found")

    # Update download tracking
    report.download_count = (report.download_count or 0) + 1
    report.last_downloaded_at = datetime.now(timezone.utc)
    await db.commit()

    # Return PDF as file download
    return FileResponse(
        io.BytesIO(report.pdf_content),
        media_type="application/pdf",
        filename=f"{report.report_title}.pdf",
    )
