from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
from typing import Any


_DEFAULT_MANAGED_TOOLS = ("nuclei", "findomain", "subfinder", "httpx", "naabu", "amass")


@dataclass(frozen=True)
class ReconftwConfigResult:
    config_path: str
    output_root: str
    content: str
    managed_tools_disabled: list[str]


def _read_env(key: str, fallback: str = "") -> str:
    return os.getenv(key, fallback).strip()


def load_snl_settings(overrides: dict[str, Any] | None = None) -> dict[str, Any]:
    opts = overrides or {}
    allowed_ifaces = str(
        opts.get("k1_vpn_allowed_interfaces")
        or _read_env("K1_VPN_ALLOWED_INTERFACES", "tun0,wg0")
    )
    active_iface = str(opts.get("k1_active_vpn_interface") or _read_env("K1_ACTIVE_VPN_INTERFACE", ""))
    proxy_url = str(opts.get("k1_residential_proxy_url") or _read_env("K1_RESIDENTIAL_PROXY_URL", ""))
    use_proxies = str(opts.get("k1_use_proxies") or _read_env("K1_USE_PROXIES", "false")).lower() in {
        "1",
        "true",
        "yes",
        "on",
    }

    return {
        "allowed_interfaces": [token.strip() for token in allowed_ifaces.split(",") if token.strip()],
        "active_interface": active_iface,
        "proxy_url": proxy_url,
        "use_proxies": use_proxies,
    }


def build_reconftw_cfg_content(
    *,
    target: str,
    snl_settings: dict[str, Any] | None = None,
    nvme_root: str | None = None,
    output_root: str | None = None,
    managed_tools: list[str] | tuple[str, ...] | None = None,
) -> str:
    snl = snl_settings or load_snl_settings()
    managed = sorted(set(str(tool).strip().lower() for tool in (managed_tools or _DEFAULT_MANAGED_TOOLS) if str(tool).strip()))
    nvme = str(nvme_root or _read_env("K1_NVME_ROOT", "/mnt/nvme"))
    output = str(output_root or _read_env("K1_WORKFLOW_OUTPUT_ROOT", "output"))
    proxy = str(snl.get("proxy_url", "")).strip()
    use_proxy = bool(snl.get("use_proxies"))
    allowed_ifaces = ",".join(snl.get("allowed_interfaces", []))
    active_iface = str(snl.get("active_interface", "")).strip()

    lines = [
        "# Auto-generated by K1 ReconftwConfig (do not hardcode secrets here)",
        f"K1_TARGET={target}",
        f"K1_SNL_ALLOWED_INTERFACES={allowed_ifaces}",
        f"K1_SNL_ACTIVE_INTERFACE={active_iface}",
        f"K1_SNL_USE_PROXIES={'true' if use_proxy else 'false'}",
        f"K1_SNL_PROXY_URL={proxy}",
        f"K1_NVME_ROOT={nvme}",
        f"K1_OUTPUT_ROOT={output}",
        f"K1_DISABLE_MANAGED_TOOLS={','.join(managed)}",
        "K1_DISABLE_RECONFTW_AUTOINSTALL=true",
        "K1_RECONFTW_SELECTIVE_MODE=true",
        "K1_RECONFTW_TUNNEL_FIRST=true",
        "",
        "# Standard Reconftw Overrides",
        f"PROXY=\"{proxy}\"" if proxy and use_proxy else "PROXY=\"\"",
        f"VPN_INTERFACE=\"{active_iface}\"" if active_iface else "VPN_INTERFACE=\"\"",
        f"INTERFACES=\"{active_iface}\"" if active_iface else "INTERFACES=\"tun0,wg0\"",
        "DEBUG=false",
        "OS=\"Linux\"",
    ]
    return "\n".join(lines) + "\n"


def write_reconftw_cfg(
    *,
    target: str,
    config_path: str | Path,
    snl_settings: dict[str, Any] | None = None,
    nvme_root: str | None = None,
    output_root: str | None = None,
    managed_tools: list[str] | tuple[str, ...] | None = None,
) -> ReconftwConfigResult:
    cfg_path = Path(config_path).expanduser().resolve()
    cfg_path.parent.mkdir(parents=True, exist_ok=True)

    content = build_reconftw_cfg_content(
        target=target,
        snl_settings=snl_settings,
        nvme_root=nvme_root,
        output_root=output_root,
        managed_tools=managed_tools,
    )
    cfg_path.write_text(content, encoding="utf-8")
    managed = sorted(set(str(tool).strip().lower() for tool in (managed_tools or _DEFAULT_MANAGED_TOOLS) if str(tool).strip()))
    return ReconftwConfigResult(
        config_path=str(cfg_path),
        output_root=str(output_root or _read_env("K1_WORKFLOW_OUTPUT_ROOT", "output")),
        content=content,
        managed_tools_disabled=managed,
    )
