"""
Project Scaffolding Module
Handles directory structure creation, code generation, and dependency management.
"""

import os
import json
import shutil
from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime


class Scaffolder:
    """
    Generates project structure and source code from architectural blueprints.
    """
    
    def __init__(self):
        self.templates_dir = Path(__file__).parent / "templates"
        
    def create_project(self, blueprint: Dict[str, Any], 
                      output_dir: str,
                      project_name: str) -> Path:
        """
        Create complete project structure from blueprint.
        
        Args:
            blueprint: Architecture specification from Architect
            output_dir: Base directory for projects
            project_name: Name of the project
            
        Returns:
            Path to created project directory
        """
        base_path = Path(output_dir) / project_name
        base_path.mkdir(parents=True, exist_ok=True)
        
        # Create directory structure
        (base_path / "src").mkdir(exist_ok=True)
        (base_path / "tests").mkdir(exist_ok=True)
        (base_path / "docs").mkdir(exist_ok=True)
        (base_path / "config").mkdir(exist_ok=True)
        
        # Generate source files
        self._generate_main_file(base_path, blueprint)
        self._generate_module_files(base_path, blueprint)
        self._generate_requirements(base_path, blueprint)
        self._generate_config_files(base_path, blueprint)
        self._generate_readme(base_path, blueprint)
        self._generate_tests(base_path, blueprint)
        
        return base_path
    
    def _generate_main_file(self, project_path: Path, blueprint: Dict[str, Any]):
        """Generate the main entry point file."""
        components = blueprint.get('components', [])
        project_name = blueprint.get('project_name', 'tool')
        
        # Generate imports based on components
        imports = [
            "import argparse",
            "import sys",
            "import json",
            "import logging",
            "from pathlib import Path",
            "from colorama import init, Fore, Style"
        ]
        
        # Add specific imports based on components
        for comp in components:
            if comp['type'] == 'scanner':
                imports.append("from primitives.scanner import TCPScanner, UDPScanner")
            elif comp['type'] == 'exploit':
                imports.append("from primitives.exploit import RemoteExploit, LocalExploit")
            elif comp['type'] == 'parser':
                imports.append("from primitives.parser import LogParser, JSONAnalyzer")
        
        # Generate main logic
        main_logic = self._generate_main_logic(components, blueprint)
        
        content = f'''#!/usr/bin/env python3
"""
{project_name}
Generated by Forge Engine
Architecture: {blueprint.get('architecture_type', 'linear')}
Description: {blueprint.get('description', 'Security tool')}
"""

{'\\n'.join(imports)}

# Initialize colorama
init(autoreset=True)

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class {self._to_class_name(project_name)}:
    """
    Main tool implementation.
    Architecture Type: {blueprint.get('architecture_type', 'linear')}
    """
    
    def __init__(self, config: dict = None):
        self.config = config or {{}}
        self.results = {{}}
        {self._generate_init_components(components)}
    
    {self._generate_methods(components, blueprint)}
    
    def run(self, args):
        """Main execution entry point."""
        logger.info(f"Starting {{args}}")
        
        try:
            {main_logic}
            return self.results
        except Exception as e:
            logger.error(f"Execution failed: {{e}}")
            raise


def main():
    parser = argparse.ArgumentParser(
        description="{blueprint.get('description', 'Security tool')}",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Security Considerations:
{chr(10).join(' - ' + note for note in blueprint.get('security_considerations', []))}
"""
    )
    
    parser.add_argument('--target', '-t', help='Target host/IP')
    parser.add_argument('--port', '-p', type=int, help='Target port')
    parser.add_argument('--file', '-f', help='Input file path')
    parser.add_argument('--output', '-o', help='Output file path')
    parser.add_argument('--verbose', '-v', action='store_true', help='Verbose output')
    parser.add_argument('--threads', type=int, default=10, help='Number of threads')
    
    args = parser.parse_args()
    
    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)
    
    tool = {self._to_class_name(project_name)}()
    results = tool.run(args)
    
    if args.output:
        with open(args.output, 'w') as f:
            json.dump(results, f, indent=2)
        print(f"{{Fore.GREEN}}Results saved to {{args.output}}{{Style.RESET_ALL}}")
    else:
        print(json.dumps(results, indent=2))


if __name__ == '__main__':
    main()
'''
        
        main_file = project_path / "src" / "main.py"
        main_file.write_text(content)
        main_file.chmod(0o755)
    
    def _generate_init_components(self, components: List[Dict]) -> str:
        """Generate component initialization code."""
        lines = []
        for comp in components:
            if comp['type'] != 'interface':
                class_name = comp['primitive_class']
                config = json.dumps(comp['configuration'])
                lines.append(f"        self.{comp['name']} = {class_name}(config={config})")
        return '\n'.join(lines) if lines else "        pass"
    
    def _generate_methods(self, components: List[Dict], blueprint: Dict) -> str:
        """Generate method implementations for components."""
        methods = []
        arch_type = blueprint.get('architecture_type', 'linear')
        
        for comp in components:
            if comp['type'] == 'interface':
                continue
                
            method_name = f"execute_{comp['name']}"
            inputs = comp.get('inputs', [])
            input_params = ', '.join(inputs) if inputs else '**kwargs'
            
            method_body = f'''
    def {method_name}(self, {input_params}):
        """Execute {comp['name']} component."""
        logger.info("Executing {comp['name']}...")
        try:
            result = self.{comp['name']}.execute({input_params})
            self.results['{comp['name']}'] = result
            return result
        except Exception as e:
            logger.error(f"{comp['name']} failed: {{e}}")
            raise
'''
            methods.append(method_body)
        
        return '\n'.join(methods)
    
    def _generate_main_logic(self, components: List[Dict], blueprint: Dict) -> str:
        """Generate the main execution flow logic."""
        arch_type = blueprint.get('architecture_type', 'linear')
        flow = blueprint.get('execution_flow', [])
        
        if not flow:
            # Default linear execution
            lines = []
            for comp in components:
                if comp['type'] != 'interface':
                    lines.append(f"self.execute_{comp['name']}(args.target)")
            return '\n            '.join(lines)
        
        # Generate based on flow specification
        lines = []
        for step in flow:
            comp_name = step['component']
            action = step['action']
            
            if action == 'initialize':
                lines.append(f"# Initialize {comp_name}")
            elif action == 'process':
                input_from = step.get('input_from', 'previous')
                lines.append(f"result_{comp_name} = self.execute_{comp_name}(args.target)")
            elif action == 'execute':
                lines.append(f"self.execute_{comp_name}(args.target)")
        
        return '\n            '.join(lines) if lines else "pass"
    
    def _generate_module_files(self, project_path: Path, blueprint: Dict[str, Any]):
        """Generate additional module files if needed."""
        # Create __init__.py
        (project_path / "src" / "__init__.py").write_text(f'"""{blueprint["project_name"]}"""\n')
        
        # Copy primitives if needed (in real implementation, would reference library)
        primitives_dir = project_path / "src" / "primitives"
        primitives_dir.mkdir(exist_ok=True)
        (primitives_dir / "__init__.py").write_text('"""Primitives"""\n')
    
    def _generate_requirements(self, project_path: Path, blueprint: Dict[str, Any]):
        """Generate requirements.txt from dependencies."""
        deps = blueprint.get('dependencies', [])
        
        # Add standard dependencies
        all_deps = set(deps)
        all_deps.add('colorama>=0.4.4')
        all_deps.add('tqdm>=4.62.0')
        
        content = f"""# Auto-generated requirements for {blueprint['project_name']}
# Generated: {datetime.now().isoformat()}

{chr(10).join(sorted(all_deps))}

# Development dependencies
pytest>=7.0.0
pytest-cov>=3.0.0
black>=22.0.0
flake8>=4.0.0
"""
        
        (project_path / "requirements.txt").write_text(content)
    
    def _generate_config_files(self, project_path: Path, blueprint: Dict[str, Any]):
        """Generate configuration files."""
        config = {
            "project_name": blueprint['project_name'],
            "architecture": blueprint['architecture_type'],
            "components": [c['name'] for c in blueprint['components']],
            "created_at": datetime.now().isoformat(),
            "settings": {
                "timeout": 30,
                "max_threads": 100,
                "log_level": "INFO"
            }
        }
        
        config_file = project_path / "config" / "settings.json"
        config_file.write_text(json.dumps(config, indent=2))
    
    def _generate_readme(self, project_path: Path, blueprint: Dict[str, Any]):
        """Generate README.md documentation."""
        content = f"""# {blueprint['project_name']}

{blueprint['description']}

## Architecture
Type: {blueprint['architecture_type']}

### Components
{chr(10).join(f"- **{c['name']}** ({c['type']}): {c['primitive_class']}" for c in blueprint['components'])}

## Security Considerations
{chr(10).join(f"- {note}" for note in blueprint.get('security_considerations', []))}

## Installation
```bash
pip install -r requirements.txt
```

## Usage
```bash
python src/main.py --help
```

---
Generated by Forge Engine on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
        (project_path / "README.md").write_text(content)
        
    def _generate_tests(self, project_path: Path, blueprint: Dict[str, Any]):
        """Generate basic test scaffolding."""
        test_content = f"""import pytest
import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from main import {self._to_class_name(blueprint['project_name'])}

def test_initialization():
    tool = {self._to_class_name(blueprint['project_name'])}()
    assert tool is not None
    assert tool.results == {{}}

if __name__ == '__main__':
    pytest.main([__file__])
"""
        (project_path / "tests" / "test_main.py").write_text(test_content)
        (project_path / "tests" / "__init__.py").write_text("")

    def _to_class_name(self, name: str) -> str:
        """Convert snake_case or kebab-case to CamelCase."""
        return "".join(x.capitalize() for x in name.replace("-", "_").split("_"))
