from .base import Base

# Auth models — imported first so Tenant/User are registered in the SQLAlchemy
# class registry before campaign.py resolves relationship("Tenant") strings.
from apps.backend.src.auth.models import APIToken, Tenant, User, UserRole

from .bug_bounty import (
    AdaptiveScheduleActionRecord,
    AgentEvaluationRecord,
    AgentExecutionRecord,
    AgentRegistryRecord,
    AlertOutcomeRecord,
    AnalystQueueItem,
    AnalystCaseRecord,
    DecisionOutcomeRecord,
    DuplicateRiskRecord,
    EvidenceCompletenessRecord,
    FeedbackSignalRecord,
    HuntReadinessRecord,
    HuntScheduleJob,
    NotificationAlertRecord,
    OpportunityInferenceRecord,
    OpportunitySelectionRecord,
    RecommendationOutcomeRecord,
    SignalIntelligenceRecord,
    SwarmReasoningRecord,
    TargetYieldScoreRecord,
    VulnerabilityPredictionRecord,
    WorkflowPerformanceRecord,
    WorkflowRecommendationRecord,
    WorkflowDeltaRecord,
    TargetPerformanceRecord,
)
from .campaign import (
    ApprovalGate,
    Artifact,
    AuditEvent,
    CampaignRun,
    ExecutionBranch,
    Observation,
    PhaseJob,
    Program,
    ScanNote,
    ScopeTarget,
    SubmissionDraft,
    ToolExecution,
)
from .enums import (
    ApprovalGateStatusEnum,
    ArtifactTypeEnum,
    BranchStatusEnum,
    CampaignStatusEnum,
    CorrelationActionEnum,
    ExecutionStatusEnum,
    FindingStatusEnum,
    HILApprovalStatusEnum,
    IntentionSourceEnum,
    IntentionTypeEnum,
    ObservationTypeEnum,
    PhaseJobStatusEnum,
    RiskPolicyClassEnum,
    SeverityEnum,
    StageRunStatusEnum,
    ToolExecutionStatusEnum,
    WorkflowRunStatusEnum,
)
from .execution import ExecutionContextRecord
from .hil import AuditMerkleRoot, Evidence, Finding, HILApproval, Report
from .hil_extra import ProgramScope
from .intention import IntentionRecord
from .workflow import CorrelationRecord, StageRun, WorkflowFinding, WorkflowRun

__all__ = [
    "Base",
    "SeverityEnum",
    "FindingStatusEnum",
    "HILApprovalStatusEnum",
    "ExecutionStatusEnum",
    "CampaignStatusEnum",
    "BranchStatusEnum",
    "PhaseJobStatusEnum",
    "ApprovalGateStatusEnum",
    "ToolExecutionStatusEnum",
    "ArtifactTypeEnum",
    "ObservationTypeEnum",
    "IntentionSourceEnum",
    "IntentionTypeEnum",
    "RiskPolicyClassEnum",
    "WorkflowRunStatusEnum",
    "StageRunStatusEnum",
    "CorrelationActionEnum",
    "HuntScheduleJob",
    "HuntReadinessRecord",
    "WorkflowDeltaRecord",
    "AnalystQueueItem",
    "NotificationAlertRecord",
    "AnalystCaseRecord",
    "FeedbackSignalRecord",
    "DecisionOutcomeRecord",
    "WorkflowPerformanceRecord",
    "TargetPerformanceRecord",
    "RecommendationOutcomeRecord",
    "AlertOutcomeRecord",
    "SignalIntelligenceRecord",
    "OpportunityInferenceRecord",
    "SwarmReasoningRecord",
    "AdaptiveScheduleActionRecord",
    "AgentRegistryRecord",
    "AgentExecutionRecord",
    "AgentEvaluationRecord",
    "TargetYieldScoreRecord",
    "DuplicateRiskRecord",
    "EvidenceCompletenessRecord",
    "VulnerabilityPredictionRecord",
    "OpportunitySelectionRecord",
    "WorkflowRecommendationRecord",
    "Finding",
    "Evidence",
    "HILApproval",
    "Report",
    "AuditMerkleRoot",
    "ProgramScope",
    "ExecutionContextRecord",
    "Program",
    "ScopeTarget",
    "CampaignRun",
    "ExecutionBranch",
    "PhaseJob",
    "ApprovalGate",
    "ToolExecution",
    "Observation",
    "Artifact",
    "ScanNote",
    "SubmissionDraft",
    "AuditEvent",
    "IntentionRecord",
    "WorkflowRun",
    "StageRun",
    "WorkflowFinding",
    "CorrelationRecord",
]
