from __future__ import annotations

from enum import Enum


class SeverityEnum(str, Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class FindingStatusEnum(str, Enum):
    NEW = "NEW"
    IN_REVIEW = "IN_REVIEW"
    HIL_APPROVED = "HIL_APPROVED"
    SUBMITTED = "SUBMITTED"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"
    DUPLICATE = "DUPLICATE"


class HILApprovalStatusEnum(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ExecutionStatusEnum(str, Enum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class CampaignStatusEnum(str, Enum):
    CREATED = "CREATED"
    READY = "READY"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"


class BranchStatusEnum(str, Enum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"


class PhaseJobStatusEnum(str, Enum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    CANCELED = "CANCELED"


class ApprovalGateStatusEnum(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DEFERRED = "DEFERRED"
    EXPIRED = "EXPIRED"
    CANCELED = "CANCELED"


class ToolExecutionStatusEnum(str, Enum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"


class ArtifactTypeEnum(str, Enum):
    RAW_OUTPUT = "RAW_OUTPUT"
    LOG = "LOG"
    HTTP_TRACE = "HTTP_TRACE"
    SCREENSHOT = "SCREENSHOT"
    REQUEST_CAPTURE = "REQUEST_CAPTURE"
    RESPONSE_CAPTURE = "RESPONSE_CAPTURE"
    EVIDENCE_BUNDLE = "EVIDENCE_BUNDLE"
    REPORT_DRAFT = "REPORT_DRAFT"
    OTHER = "OTHER"


class ObservationTypeEnum(str, Enum):
    DISCOVERY = "DISCOVERY"
    SIGNAL = "SIGNAL"
    VULNERABILITY = "VULNERABILITY"
    VALIDATION = "VALIDATION"
    CONTEXT = "CONTEXT"
    DECISION = "DECISION"
    METRIC = "METRIC"
    OTHER = "OTHER"


class IntentionSourceEnum(str, Enum):
    USER = "USER"
    AGENT = "AGENT"
    SYSTEM = "SYSTEM"
    POLICY_ENGINE = "POLICY_ENGINE"
    OPERATOR = "OPERATOR"


class IntentionTypeEnum(str, Enum):
    CAMPAIGN_START = "CAMPAIGN_START"
    BRANCH_PLAN = "BRANCH_PLAN"
    PHASE_EXECUTION = "PHASE_EXECUTION"
    TOOL_EXECUTION = "TOOL_EXECUTION"
    APPROVAL_REQUEST = "APPROVAL_REQUEST"
    APPROVAL_DECISION = "APPROVAL_DECISION"
    NOTE = "NOTE"
    REPORT_DRAFT = "REPORT_DRAFT"
    POLICY_OVERRIDE = "POLICY_OVERRIDE"
    SYSTEM_MAINTENANCE = "SYSTEM_MAINTENANCE"


class RiskPolicyClassEnum(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    RESTRICTED = "RESTRICTED"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    POLICY_EXCEPTION = "POLICY_EXCEPTION"


class WorkflowRunStatusEnum(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"


class StageRunStatusEnum(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"


class CorrelationActionEnum(str, Enum):
    CREATED = "CREATED"
    ATTACHED = "ATTACHED"
    ALREADY_LINKED = "ALREADY_LINKED"
    DEDUPLICATED = "DEDUPLICATED"
    CONTEXT_ONLY = "CONTEXT_ONLY"
    UNSUPPORTED = "UNSUPPORTED"
