"""ORM model for storing generated PDF reports as immutable audit records.

This module tracks all reports generated by the intelligence engine
for audit trail, retrieval, and historical analysis.
"""
from __future__ import annotations

from datetime import datetime, timezone
from uuid import UUID

from sqlalchemy import (
    Column,
    DateTime,
    Integer,
    String,
    Text,
    LargeBinary,
    func,
)
from sqlalchemy.dialects.postgresql import JSON, UUID as PGUUID
from sqlalchemy.orm import relationship

from .base import Base


class GeneratedReport(Base):
    """Store generated PDF reports as immutable records."""

    __tablename__ = "generated_reports"

    id = Column(PGUUID(as_uuid=True), primary_key=True)

    # Report metadata
    report_type = Column(String(50), nullable=False)  # per_scan, per_program, etc.
    report_title = Column(String(500), nullable=False)
    report_description = Column(Text, nullable=True)

    # Filtering specification (JSON for flexibility)
    filters = Column(JSON, nullable=False)  # What data was included

    # PDF content (stored as binary)
    pdf_content = Column(LargeBinary, nullable=False)  # Binary PDF data

    # Metrics about the report
    word_count = Column(Integer, nullable=True)  # Approximate word count
    page_count = Column(Integer, nullable=True)  # Number of pages
    file_size_bytes = Column(Integer, nullable=True)  # PDF file size

    # Audit fields
    generated_by = Column(String(255), nullable=False)  # Analyst ID who requested it
    generated_at = Column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # Tracking
    download_count = Column(Integer, default=0, server_default="0")
    last_downloaded_at = Column(DateTime(timezone=True), nullable=True)

    # Immutable timestamps
    created_at = Column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at = Column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
