from __future__ import annotations

import uuid

from sqlalchemy import Column, Float, Index, Integer, JSON, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from .base import Base
from .mixins import TimestampMixin, UTCAwareDatetime


class PraisonMission(Base, TimestampMixin):
    """Persists Praison/LangGraph mission lifecycle state to PostgreSQL.

    Written fire-and-forget at mission create, start, and complete/fail.
    Does NOT block mission execution — any DB error is logged and swallowed.
    """

    __tablename__ = "praison_missions"
    __table_args__ = (
        Index("ix_praison_missions_program_id", "program_id"),
        Index("ix_praison_missions_workflow_id", "workflow_id"),
        Index("ix_praison_missions_status", "status"),
        Index("ix_praison_missions_tenant_id", "tenant_id"),
    )

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    # Logical mission UUID generated by MissionRuntime
    mission_id = Column(Text, nullable=False, unique=True)
    tenant_id = Column(Text, nullable=True)
    workflow_id = Column(Text, nullable=False)
    program_id = Column(Text, nullable=False)
    mission_name = Column(Text, nullable=True)
    execution_mode = Column(Text, nullable=False, server_default="live")
    status = Column(Text, nullable=False, server_default="created")

    # Timestamps for key lifecycle transitions
    started_at = Column(UTCAwareDatetime, nullable=True)
    completed_at = Column(UTCAwareDatetime, nullable=True)

    # Summary counters updated at completion
    tools_executed = Column(Integer, nullable=False, server_default="0")
    artifacts_written = Column(Integer, nullable=False, server_default="0")

    # Final state snapshot (trimmed to avoid bloat — excludes raw stdout)
    final_state_summary = Column(JSON, nullable=True)
    error = Column(Text, nullable=True)

    tool_runs = relationship("PraisonToolRun", back_populates="mission", cascade="all, delete-orphan")


class PraisonToolRun(Base, TimestampMixin):
    """One row per tool invocation within a PraisonMission."""

    __tablename__ = "praison_tool_runs"
    __table_args__ = (
        Index("ix_praison_tool_runs_mission_id", "mission_id"),
        Index("ix_praison_tool_runs_tool_id", "tool_id"),
        Index("ix_praison_tool_runs_agent_id", "agent_id"),
        Index("ix_praison_tool_runs_status", "status"),
    )

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    mission_id = Column(Text, nullable=False, index=False)  # FK-like but loose coupling
    agent_id = Column(Text, nullable=True)
    tool_id = Column(Text, nullable=False)
    target = Column(Text, nullable=True)
    status = Column(Text, nullable=False, server_default="completed")
    execution_time_ms = Column(Float, nullable=True)
    # Compact result metadata — not raw stdout
    result_summary = Column(JSON, nullable=True)
    error = Column(Text, nullable=True)

    mission = relationship(
        "PraisonMission",
        primaryjoin="PraisonToolRun.mission_id == foreign(PraisonMission.mission_id)",
        back_populates="tool_runs",
        viewonly=True,
    )
